changed js to ts and added loader to movie card
ratroian/project_2_kinoteka pull request #15
Opened 2021-12-25 17:38 UTC by NataliaHuberna

2022-01-05 18:46 UTC, duhenetsaleksandr commented on src/styles/movie.css
> +    left: 50%;
add -> transform: translate(-50%, -50%);

2022-01-05 18:47 UTC, duhenetsaleksandr commented on src/styles/movie.css
> +    justify-content: center;
Why are these properties there and "display: flex;" is not?

2022-01-05 18:48 UTC, duhenetsaleksandr commented on src/styles/movie.css
> +    height: 100vh;
change to %

2022-01-05 18:48 UTC, duhenetsaleksandr commented on src/styles/movie.css
> +    background: rgba(0,0,0,0.9);
to css variable

2022-01-05 18:49 UTC, duhenetsaleksandr commented on src/scripts/movie/movie.js
> +  domElements.loaderFullScreen.classList.toggle(CLASS_HIDDEN);
fix indent

2022-01-05 18:49 UTC, duhenetsaleksandr commented on src/scripts/movies/global-var.ts
> +export const globalVar: TglobalVar = {
camelCase

2022-01-05 18:51 UTC, duhenetsaleksandr requested changes
fix comments

2022-01-06 12:29 UTC, duhenetsaleksandr approved these changes

2022-01-06 12:30 UTC, ratroian approved these changes

2022-01-06 12:31 UTC, merged