done film page
ratroian/project_2_kinoteka pull request #7
Opened 2021-12-05 19:11 UTC by shapikso

2021-12-05 19:29 UTC, duhenetsaleksandr commented on src/movie.html
> +                <div class="basic-link space-between">popularity: 80/100</div>
these are not links what to use the class "basic-link"

2021-12-05 19:30 UTC, duhenetsaleksandr commented on src/movie.html
> +                <div class="basic-btn space-between">Action</div>
these are not buttons what to use the class "basic-btn"

2021-12-05 19:32 UTC, duhenetsaleksandr commented on src/movie.html
> +            <div class="basic-link space-between">popularity: {{popularity}}/100</div>
"space-between" - this is a bad name for the class

2021-12-05 19:32 UTC, duhenetsaleksandr commented on src/movie.html
> +<script type="text/template" id="MovieTemplate">
camelCase for id name

2021-12-05 19:35 UTC, duhenetsaleksandr commented on src/styles/movie-page.css
> +   margin: 50px;
fix indent

2021-12-05 19:42 UTC, duhenetsaleksandr commented on src/styles/movie-page.css
> +    width: 1420px;
maybe a percentage relative to the parent

2021-12-05 19:43 UTC, duhenetsaleksandr commented on src/styles/movie-page.css
> +    box-sizing: border-box;
this property is already in reset.css

2021-12-05 19:44 UTC, duhenetsaleksandr commented on src/movie.html
> +                 Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.</p>
if there is too much text, it falls out of the block

2021-12-05 19:46 UTC, duhenetsaleksandr commented on src/movie.html
> +<script type="text/template" id="GenreTemplate">
camelCase for id name

2021-12-05 19:54 UTC, duhenetsaleksandr requested changes
Check the comments

2021-12-06 23:14 UTC, ratroian approved these changes
Please, check comments

2021-12-06 23:14 UTC, ratroian commented on src/movie.html
> +         background: linear-gradient( rgba(0, 0, 0, 0.700), rgba(0, 0, 0, 0.700) ), url('https://image.tmdb.org/t/p/original/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg');
styles in style.css

2021-12-06 23:14 UTC, ratroian commented on src/movie.html
> +     background: linear-gradient( rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7) ), url('{{backdrop_path}}');
styles in style.css

2021-12-06 23:14 UTC, ratroian commented on src/movie.html
> +    <div class="title">
if title - maybe use tag <h...>?

2021-12-06 23:14 UTC, ratroian commented on src/movie.html
> +         <div class="base-gaps" id="info">
maybe ul?

2021-12-06 23:14 UTC, ratroian commented on src/movie.html
> +            <div class="small-info info-block-size">{{adult}}</div>
li

2021-12-09 18:33 UTC, ratroian approved these changes

2021-12-09 18:34 UTC, duhenetsaleksandr approved these changes

2021-12-09 18:34 UTC, merged